USE master
GO

IF EXISTS (SELECT NAME FROM SYS.DATABASES WHERE NAME = 'QLBANHANG_30_MINH_B3')
DROP DATABASE QLBANHANG_30_MINH_B3
GO
CREATE DATABASE QLBANHANG_30_MINH_B3
ON(NAME='QLBANHANG_30_MINH_B3_DATA', FILENAME='E:\Nguồn Demo SQL\B3 THUC HANH LOP\QLBANHANG_30_MINH_B3.MDF')
LOG ON(NAME='QLBANHANG_30_MINH_B3', FILENAME='E:\Nguồn Demo SQL\B3 THUC HANH LOP\QLBANHANG_30_MINH_B3.LDF')
GO

USE QLBANHANG_30_MINH_B3
GO

CREATE TABLE KHACHHANG
(
	MAKH CHAR(4) PRIMARY KEY NOT NULL,
	HOTEN VARCHAR(30),
	DCHI VARCHAR(50),
	SODT CHAR(10),
	NOISINH NVARCHAR(20),
	DOANHSO FLOAT,
	NGDK DATETIME,
	CMND CHAR(12)

)

CREATE TABLE NHANVIEN
(
	MANV CHAR(4) PRIMARY KEY NOT NULL,
	HOTEN NVARCHAR(30),
	NGVL DATETIME,
	SODT CHAR(10)
)

CREATE TABLE SANPHAM
(
	MASP CHAR(5) PRIMARY KEY NOT NULL,
	TENSP NVARCHAR(50),
	DVT NVARCHAR(10),
	NUOCSX NVARCHAR(40),
	GIA FLOAT
)

CREATE TABLE HOADON
(
	SOHD CHAR(5) PRIMARY KEY NOT NULL,
	NGHD DATETIME,
	TRIGIA FLOAT,
	MAKH CHAR(4) REFERENCES KHACHHANG(MAKH),
	MANV CHAR(4) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE CTHD
(
	SOHD CHAR(5) REFERENCES HOADON(SOHD) NOT NULL,
	MASP CHAR(5) REFERENCES SANPHAM(MASP) NOT NULL,
	PRIMARY KEY(SOHD,MASP),
	SL INT
)

