USE MASTER
go

--kiểm tra database đã tồn tại chưa
if exists(select name from SYS.databases where name = 'QLDIEM_30_MINH')
drop database QLDIEM_30_MINH
go
-- 1 tạo csdl tên QLDIEM_30_MINH
create database QLDIEM_30_MINH
ON(NAME='QLDIEM_30_MINH_DATA', FILENAME = 'E:\QLDIEM_30_MINH.MDF')
LOG ON(NAME = 'QLDIEM_30_MINH', FILENAME = 'E:\QLDIEM_30_MINH.LDF')
GO

USE QLDIEM_30_MINH
GO


--TẠO BẢNG KHOA
CREATE TABLE KHOA_30_MINH
(
	MAKHOA_30_MINH CHAR(2) PRIMARY KEY NOT NULL,
	TENKHOA_30_MINH NVARCHAR(30)
)

CREATE TABLE MONHOC_30_MINH
(
	MAMH_30_MINH CHAR(2) PRIMARY KEY NOT NULL,
	TENMH_30_MINH NVARCHAR(30),
	SOTIET_30_MINH TINYINT
)

CREATE TABLE SINHVIEN_30_MINH
(
	MASV_30_MINH CHAR (3) PRIMARY KEY NOT NULL,
	HOSV_30_MINH NVARCHAR(30),
	TENSV_30_MINH NVARCHAR(30),
	PHAI_30_MINH NVARCHAR(3),
	NS_30_MINH DATE,
	NOISINH_30_MINH NVARCHAR(25),
	MAKH_30_MINH CHAR(2) references KHOA_30_MINH(MAKHOA_30_MINH) NOT NULL,
	HB_30_MINH FLOAT
)

CREATE TABLE KQ_30_MINH
(
	MASV CHAR(3) references SINHVIEN_30_MINH(MASV_30_MINH) NOT NULL,
	MAMH CHAR(2) references MONHOC_30_MINH(MAMH_30_MINH) NOT NULL,
	LANTHI TINYINT NOT NULL,
	PRIMARY KEY(MASV,MAMH,LANTHI),
	DIEM DECIMAL(4,2)
)
--NHẬP DỮ LIỆU CHO BẢNG KHOA
INSERT KHOA_30_MINH VALUES('AV', N' ANH VĂN ')
INSERT KHOA_30_MINH VALUES('TH', N' Tin Học ')
INSERT KHOA_30_MINH VALUES('AV', N' Triết ')
INSERT KHOA_30_MINH VALUES('VL', N' Vật Lý ')

--NHẬP DỮ LIỆU CHO BẢNG MÔN HỌC
INSERT MONHOC_30_MINH VALUES('01', N'Cơ sở dữ liệu', '45')
INSERT MONHOC_30_MINH VALUES('02', N'Trí tuệ nhân tạo', '45')
INSERT MONHOC_30_MINH VALUES('03', N' HÓA', '5')

--NHẬP DỮ LIỆU CHO BẢNG SINH VIÊN






